on: [push]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != format('refs/heads/{0}', github.event.repository.default_branch || 'master') }}

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-workspace
        id: setup
        with:
          ssh_key: ${{ secrets.PRIVATE_SSH_KEY }}

      - name: Print installed Erlang/Elixir versions
        shell: bash
        run: |
          echo "# BEAM information" >> $GITHUB_STEP_SUMMARY
          echo "  * Erlang/OTP version: ${{ steps.setup.outputs.otp-version}}" | tee -a $GITHUB_STEP_SUMMARY
          echo "  * Elixir version: ${{ steps.setup.outputs.elixir-version}}" | tee -a $GITHUB_STEP_SUMMARY
          echo "  * Rebar3 version: ${{ steps.setup.outputs.rebar3-version}}" | tee -a $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

      - name: Compile
        run: rebar3 compile

  commit-message:
    name: Check commit messages
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/info
        id: info

      # The `-- .` is to avoid "ambiguous argument" errors from git

      - name: Find fixup commits
        run: |
          echo Please rebase your fixup commits

          git --version
          git log --exit-code --extended-regexp \
            --grep "^(fixup|squash|amend)! " \
            --format="::error title=Must rebase before merge::%s" \
            origin/${{ github.base_ref || steps.info.outputs.default_branch }}..${{ github.ref }} \
            -- .

      - name: Find "conventional commits" style messages
        run: |
          echo Conventional Commits breaks established commit message conventions.
          echo Please follow these guidelines
          echo
          echo https://github.blog/2022-06-30-write-better-commits-build-better-projects/
          echo https://www.tpope.net

          git --version
          git log --exit-code --extended-regexp --regexp-ignore-case \
            --grep "^[a-z]+:" \
            --format="::error title=Must follow commit guidelines, see step output::%s" \
            origin/${{ github.base_ref || steps.info.outputs.default_branch }}..${{ github.ref }} \
            -- .

      - name: Find missing title cased messages
        run: |
          git --version
          ! git log \
            --format="::error title=Must be properly capitalized::%s" \
            origin/${{ github.base_ref || steps.info.outputs.default_branch }}..${{ github.ref }} \
            -- . \
          | grep '^::.*::[a-z]'

  format:
    name: Code formatting
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-workspace
        id: setup
        with:
          ssh_key: ${{ secrets.PRIVATE_SSH_KEY }}

      - name: Run erlfmt
        shell: bash
        run: |
          set -o pipefail
          rebar3 fmt --check --verbose 2>&1 \
          | sed -E 's/([^:]+):([0-9]+): (.+)/::error file=\1,line=\2::\3/g'

  xref:
    name: Xref cross-reference analyzer
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-workspace
        id: setup
        with:
          ssh_key: ${{ secrets.PRIVATE_SSH_KEY }}

      - name: Run Xref
        run: rebar3 xref

  docs:
    name: ExDoc documentation
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-workspace
        id: setup
        with:
          ssh_key: ${{ secrets.PRIVATE_SSH_KEY }}

      - name: Generate documentation
        run: rebar3 ex_doc

  dialyzer:
    name: Dialyzer type checker
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-workspace
        id: setup
        with:
          plt: true
          ssh_key: ${{ secrets.PRIVATE_SSH_KEY }}

      - name: Dialyzer
        run: rebar3 dialyzer

  eunit:
    name: EUnit tests
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-workspace
        id: setup
        with:
          ssh_key: ${{ secrets.PRIVATE_SSH_KEY }}

      - name: Unit tests
        run: rebar3 eunit --cover

      - name: Upload coverage
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: eunit.coverdata
          path: _build/test/cover/eunit.coverdata

  coverage:
    name: Coverage report
    if: ${{ success() || failure() }}
    needs: [eunit]
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-workspace
        id: setup
        with:
          ssh_key: ${{ secrets.PRIVATE_SSH_KEY }}

      - name: Download eunit.coverdata
        uses: actions/download-artifact@v3
        with:
          name: eunit.coverdata
          path: coverage

      - name: Generate coverage report
        run: |
          mkdir -p _build/test/cover
          mv coverage/eunit.coverdata _build/test/cover/
          rebar3 cover
          rebar3 covertool

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: |
            _build/test/cover/
            _build/test/covertool/kivra_core.covertool.xml
            !*.coverdata
            !cover.log